### ISSUE TITLE
能否自动去掉json中的转义符号

### ISSUE THREAD

**Issue by xfhxly** [playGitboy/JsonPath-Plus-Extractor#1]
可否加个功能：自动去掉转义符号。

**Comment by playGitboy** [comment]
> 可否加个功能：自动去掉转义符号。

具体想实现什么效果或功能？可否举一两个例子或截图具体举例说明？

**Comment by wxk0248** [comment]
格式化可以自动移除\n或者\r\n，\\"替换为"

**Comment by playGitboy** [comment]
文字描述歧义性比较强，举具体的例子对比说明或者截图演示会好很多  
按理解更新了1.4版，未知是否你们说的效果
