### ISSUE TITLE
希望添加命令行启动

### ISSUE THREAD

**Issue by kihlh** [playGitboy/JsonPath-Plus-Extractor#2]
希望添加命令行启动 输入一个json文件的路径就直接显示此文件

**Comment by playGitboy** [comment]
> 希望添加命令行启动 输入一个json文件的路径就直接显示此文件

更新v1.5版本，新增命令行启动支持，你可以测试一下

**Comment by kihlh** [comment]
哇塞，感谢作者大大，祝作者大大生十个宝贝
![image](https://github.com/playGitboy/JsonPath-Plus-Extractor/assets/62889891/f65f85b6-64fd-4ee3-a908-18ef0de55a63)
